
networks:
    microservices:
        driver: bridge

services:
    laravel:
        build:
            args:
                user: romulo
                uid: 1000
            context: ./
            dockerfile: docker/php/Dockerfile
        image: laravel-app
        restart: unless-stopped
        container_name: laravel
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - microservices

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx_laravel
        ports:
            -   8000:80
            -   443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        container_name: mysql_laravel
        ports:
            - 33061:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker/.mysql/:/var/lib/mysql
        networks:
            - microservices

    queue:
        build:
            args:
                user: romulo
                uid: 1000
            context: ./
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        container_name: queue
        volumes:
            - ./:/var/www
        depends_on:
            -   redis
        networks:
            - microservices

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - microservices
